### ISSUE TITLE
Research Pruning Methods

### ISSUE THREAD

**Issue by HNorderhus** [HNorderhus/cracknet#2]

**Comment by HNorderhus** [comment]
After a super quick research, one library seems to be https://github.com/open-mmlab/mmrazor. Check for other

**Comment by ben-z-original** [comment]
Try to find relevant literature (frequently cited, CVPR, etc.). 

~1 Day with substantial depth!

**Comment by ben-z-original** [comment]
Apparently PyTorch provides some built-in functions for pruning. That might also give a coarse overview of general pruning approaches. I only skimmed; there seem to be _local_ and _global_ pruning techniques:
https://pytorch.org/tutorials/intermediate/pruning_tutorial.html

There might be good for the implementation part, see the respective issue.
